//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace UmbracoBlog.Web.PublishedContentModels
{
	/// <summary>SEO Meta Base</summary>
	[PublishedContentModel("SEOMetaBase")]
	public partial class SeometaBase : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "SEOMetaBase";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SeometaBase(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SeometaBase, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// SEO Description: Keywords that describe the content of the page. This is considered optional since most modern search engines don't use this anymore
		///</summary>
		[ImplementPropertyType("seoDescription")]
		public string SeoDescription
		{
			get { return this.GetPropertyValue<string>("seoDescription"); }
		}

		///<summary>
		/// SEO Keywords
		///</summary>
		[ImplementPropertyType("seoKeywords")]
		public IEnumerable<string> SeoKeywords
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("seoKeywords"); }
		}

		///<summary>
		/// SEO Title: This is the first text in a google search result. The ideal length is between 40 and 60 characters
		///</summary>
		[ImplementPropertyType("seoTitle")]
		public string SeoTitle
		{
			get { return this.GetPropertyValue<string>("seoTitle"); }
		}
	}
}
