//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace UmbracoBlog.Web.PublishedContentModels
{
	/// <summary>SOME Meta Base</summary>
	[PublishedContentModel("SoMeMetaBase")]
	public partial class SoMeMetaBase : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "SoMeMetaBase";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SoMeMetaBase(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SoMeMetaBase, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// SoMe Description
		///</summary>
		[ImplementPropertyType("soMeDescription")]
		public string SoMeDescription
		{
			get { return this.GetPropertyValue<string>("soMeDescription"); }
		}

		///<summary>
		/// SoMe Images
		///</summary>
		[ImplementPropertyType("soMeImages")]
		public IEnumerable<IPublishedContent> SoMeImages
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("soMeImages"); }
		}

		///<summary>
		/// SoMe Title
		///</summary>
		[ImplementPropertyType("soMeTitle")]
		public string SoMeTitle
		{
			get { return this.GetPropertyValue<string>("soMeTitle"); }
		}
	}
}
